name: chat_kit_example
description: "Example host app for the chat_kit package."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.12.1

dependencies:
  chat_kit:
    path: ../
  firebase_auth: ^6.5.2
  firebase_core: ^4.10.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true
